### ISSUE TITLE
Firefox shutdown hangs/delayed

### ISSUE THREAD

**Issue by Filbuntu** [Lusito/dict.cc-translation#22]
Hi! 
First I want to thank you for the great add-on, it has helped me many times!

For some months I have a problem with shutting down Firefox. It takes an unusually long time. First I thought it would be a problem with Firefox itself but some research revealed it has to do with the dict.cc-add-on. If I turn it off, Firefox shuts down quickly. I use Dict.cc Translation 4.2.0 on Firefox 49.0 in Ubuntu Linux 16.04.

When I start it from the command line, I see following recurrent line (dozens) when I quit Firefox:
JavaScript error: , line 0: TypeError: can't access dead object
JavaScript error: , line 0: TypeError: can't access dead object
JavaScript error: , line 0: TypeError: can't access dead object
JavaScript error: , line 0: TypeError: can't access dead object
JavaScript error: , line 0: TypeError: can't access dead object

I don't get this when the add-on is disabled.

Thanks for any help in advance,

Dan

**Comment by SebastianZ** [comment]
I experienced the same on Windows 10. With dict.cc enabled it takes at least half a minute to close Firefox (on a slow laptop). When it's disabled it closes within a few seconds.

I didn't check for the errors yet, though.

Sebastian

**Comment by Lusito** [comment]
Sorry about the delay.. I can't reproduce this on windows 7 or xubuntu. I'll try to investigate it further, tho I wonder if it's maybe a combination of your settings or other addons which are part of the problem.
Maybe you could try with a clean firefox profile?
Thanks for reporting.

**Comment by Filbuntu** [comment]
Hi Lusito
Thanks a lot for looking into this. I also tried the dict.cc-add-on in
a new profile of Firefox (Ubuntu 16.04) and the problem did not occur.
So I disabled my many add-ons in groups at the time with the dict-cc-
add-on enabled in my normal Firefox profile but the problem still
persisted. Maybe another setting affects the add-on, but which one and
how to find out?
Have a great weekend Dan

**Comment by Lusito** [comment]
Hi Dan, thanks for testing this.
All of your custom settings are stored in the [pref.js file](http://kb.mozillazine.org/Prefs.js_file).
Copy that file to your new profile to see if the problem is related to those settings.

- If it is, you could try resetting those settings back to default one by one (using about:config).
  I'd probably reset settings in groups first to get it done faster.
  Start with the searchdictcc settings, move on to other extension settings, etc..
- If it is not, try copying the contents of your old profile folder to your new profile folder and remove files & folders until the problem goes away.

I know it's a lot of work, but I'm not sure there is a different way.
Once you find the issue, get back to me and I'll do my best to reproduce and fix it.

**Comment by Filbuntu** [comment]
Hi Lusito

Thanks for your feedback. In the meantime the new versions of Firefox
eliminated the problem and it has not returned. Great!

Dan

**Comment by Lusito** [comment]
Thanks for the update.
