### ISSUE TITLE
It does not work with ff 52.0.1

### ISSUE THREAD

**Issue by bitstreamout** [Lusito/dict.cc-translation#26]
the configuration in the Preferences  menu is not respected as well as it does not work at all.  No translation of highlighted Text with Ctrl+Alt-Click ... only the word Loading is shown.  Similar to the menubar entry as there is also no translation shown.

Maybe this is a misconfiguration? If so it would be nice to know where to change this ... maybe with the help of an external editor ;)

**Comment by Lusito** [comment]
Sorry, firefox 52 broke the add-on completely (not my fault btw). I have a new (rewritten from almost scratch) web-extension version in the pipeline, but mozilla has yet to review it.

**Comment by bitstreamout** [comment]
On Mon, Mar 27, 2017 at 01:21:54AM -0700, Lusito wrote:
> Sorry, firefox 52 broke the add-on completely (not my fault btw). I have a new (rewritten from almost scratch) web-extension version in the pipeline, but mozilla has yet to review it.
> 

Oh ... no need to say sorry. I'm aware that firefox upstream is currently breaking
the own API :(

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by stax76** [comment]
Looking forward for the web extension version, your add-on is very useful, thanks.

**Comment by bitstreamout** [comment]
Just for your information I had reported this on bugzilla of FF, see https://bugzilla.mozilla.org/show_bug.cgi?id=1355487

**Comment by valenting** [comment]
Hi everyone,
Sorry my changeset broke this addon. A few months ago we changed the URL parser to reject invalid characters in the hostname, so now http://*.dict.cc/ from package.json gets rejected.
The easy fix would be to specify the exact subdomains you need.

**Comment by Lusito** [comment]
@valenting: Thanks for the information, but why is * suddenly illegal? It works in the web-extension version and it has worked in previous versions of firefox (i.e. there had to be some code to handle the asterisk).
Will this change for the web-extension permissions as well?

I have the working web-extension version waiting in line for approval on AMO and since it's currently taking forever to get it approved (probably due to everyone moving to web-extensions right now), I don't want to create yet another upload, which would reset the queue position.

**Comment by valenting** [comment]
@Lusito this change was made to make the URL parser more spec compliant.
The handling of * in web-extensions could be different. It's best to check your web-extension on Nightly to make sure permissions work correctly. Otherwise, let me know and I'll try to fix it.
I'll ask around if we can bump you up the queue, since your native addon has broken due to a platform change.

**Comment by Lusito** [comment]
So if nightly works with *, it will keep working?
Will try it tomorrow. Thanks for the help.

**Comment by valenting** [comment]
@Lusito relevant discussion in #addon-reviewers

(20:13:08) valentin: Spoji: bug 1355487 broke the dict.cc addon. They are currently waiting for review on a web-extension update. I was wondering if there was any way to bump them up the queue, so the users don't miss out
(20:19:00) Spoji: We currently having a surge of people asking for expedited reviews, note that this add-on seems to have been migrated to web-extensions which make things longer to review as well. Also, looking quickly at the sources, I think there is some security issues that will need to be fixed by the dev before moving this update to production.
(20:30:51) limpkin: holy sh*t, am i seeing it right? waiting list position not reset when an update is pushed?
(20:34:34) Spoji: limpkin: That's right :)
(20:34:57) TheOne: I got fixed very quickly after someone filed a bug

So, I think you could technically push an update without loosing the waiting list position.

**Comment by Lusito** [comment]
Any hints on the security issues? Not sure why there would be security issues that haven't been there in the native-sdk-version.
So If I push a version with only the asterisk fix, it should be done quickly?

**Comment by valenting** [comment]
I assume so. Please check with Spoji on the #addon-reviewers IRC channel

**Comment by Lusito** [comment]
We have a working version available again \0/
It's the last (old) version with just the fix to get it done faster.
Now the web-extension version can take a bit longer for all I care.

Thanks @valenting and Spoji and TheOne from #addon-reviewers
