### ISSUE TITLE
mac support for rocker gestures

### ISSUE THREAD

**Issue by CennoxX** [Lusito/dict.cc-translation#34]
If I'm using a mac, the translation doesn't appear when using rocker gestures. Context menu and quick click (with the right keys) work.
Interestingly enough, if I "enable right click for more options", these options will be shown with rocker gestures (and with a click on the translation, I can get to these). But on left click, nothing will appear.
I used the version from 26th march 2018.

**Comment by CennoxX** [comment]
I am using a regular pc mouse, this happens on every page and I am using the Firefox version 59.0.2.

**Comment by Lusito** [comment]
@CennoxX @ei-ke
So, here I am almost 3 years later and I finally know why this is happening, since I was able to reproduce it.

It seems, that on linux and mac, the context menu shows up on mouse-down rather than mouse-up (so that you can select a menu-item with just one mouse-down-up action).

When using a rocker gesture from right to left will look like this to the browser:
- right mouse down => detected
- left mouse down => no event (but context menu is closed) -> this is where windows detects the click and linux/mac don't.
- left mouse up => up event now shows since the context menu is gone

This didn't work, since I do the translation only on mouse-down. I've found a way to make rocker gestures work, although it's a bit more work for linux/mac users:
- When I detect a left-mouse-up when right-mouse is still down, I show the translation.
- What this means is that a rocker gesture should be done like this:
- right mouse down
- left mouse down
- left mouse up => triggers translation
- right mouse up

It takes a bit getting used to, but I think once it's in the muscle memory, it should be okay.
I will release an updated version soon.

**Comment by ei-ke** [comment]
Currently I'm with Brave and forgot about this issue :)
